name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout GitHub Project
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./src
            push: true
            file: ./src/Dockerfile
            tags: |
              tadeuaugusto/fake-shop:latest
              tadeuaugusto/fake-shop:v${{ github.run_number }}

    cd:
      runs-on: ubuntu-latest
      needs: [ci]
      permissions:
        id-token: write
        contents: read
        actions: read
      steps:
        - name: Checkout GitHub Project
          uses: actions/checkout@v4

        - name: AWS Authentication
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Kubectl Configuration
          run: aws eks update-kubeconfig --name eks-cluster-k8s

        - name: Deploy Manifests on Kubernetes
          uses: Azure/k8s-deploy@v5
          with:
             manifests: |
               ./k8s/deployment.yaml
             images: |
                tadeuaugusto/fake-shop:v${{ github.run_number }}